# Generated by Django 2.1.1 on 2018-09-28 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Reference')),
                ('screening_identifier', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Screening Identifier')),
                ('age_in_years', models.IntegerField(verbose_name='Age in years.')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('citizenship', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is subject a citizen of botswana?')),
                ('married_to_citizen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='If not citizen, are they legally married to a motswana?')),
                ('marriage_proof', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='has subject provided proof of marriage? Marriage certificate.')),
                ('literacy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is subject literate?')),
                ('has_witness_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Does the subject have a literate witness available with them ?')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=8, verbose_name="What is the subject's maritalstatus?")),
                ('living_arr', models.CharField(choices=[('ALONE', 'Alone'), ('PARTNER', 'Partner'), ('SIBLINGS', 'Siblings'), ('OTHER', 'Other'), ('NOT ANSWERING', "Don't want to answer")], max_length=30, verbose_name='Who does the subject currently live with?')),
                ('number_of_spouses_f', models.IntegerField(verbose_name="How many wives does the subject's husband have(including traditional marriage), including the subject?")),
                ('number_of_spouses_m', models.IntegerField(verbose_name='How many wives does the subject have, including traditionalmarriage?')),
                ('employment_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is the subject currently employed?')),
                ('work_type', models.CharField(choices=[('CASUAL EMPLOYMENT', 'Casual Employment'), ('SEASONAL EMPLOYMENT', 'Seasonal Employment'), ('FW FULL TIME', 'Formal Wage (Full-Time)'), ('FW PART TIME', 'Formal Wage (Part-Time)'), ('SE AGRICULTURE', 'Self Employed in Agriculture'), ('SE FULL TIME', 'Self Employed Full Time'), ('SE PART TIME', 'Self Employed Part Time'), ('NOT ANSWERING', "Don't want to answer"), ('OTHER', 'Other')], max_length=30, verbose_name='What type of work does the subject do?')),
                ('income_earnings', models.CharField(choices=[('None', 'No income'), ('1-199', '1-199 pula'), ('200-499', '200-499 pula'), ('500-999', '500-999 pula'), ('1000-4999', '1000-4999 pula'), ('5000-10000', '5000-10000 pula'), ('>10000', 'More than 10000 pula'), ('NOT ANSWERING', "Don't want to answer")], max_length=10, verbose_name='In the past month, how much money did the subjectearn from the work they did or received in payment?')),
                ('community_activity', models.CharField(choices=[('VERY', 'Very Active'), ('SOMEWHAT', 'Somewhat Active'), ('NOT ACTIVE', 'Not active'), ('NOT ANSWERING', "Don't want to answer")], max_length=20, verbose_name='How active is the subject in community activitiessuch as Motshelo, Syndicate, PTA, VDC, Mophato anddevelopment of the community that surrounds the subject?')),
                ('voted', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=15, verbose_name='Did the subject vote during the last local government election?')),
            ],
        ),
    ]
