# Generated by Django 2.1.1 on 2018-09-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantscreening',
            name='eligible',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
