# Generated by Django 2.1.1 on 2018-10-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_screening', '0002_participantscreening_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantscreening',
            name='reasons_ineligible',
            field=models.TextField(editable=False, max_length=150, null=True, verbose_name='Reason not eligible'),
        ),
    ]
