# Generated by Django 2.1.1 on 2018-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_screening', '0003_participantscreening_reasons_ineligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantscreening',
            name='community_activity',
            field=models.CharField(choices=[('VERY', 'Very Active'), ('SOMEWHAT', 'Somewhat Active'), ('NOT ACTIVE', 'Not active'), ('NOT ANSWERING', "Don't want to answer")], max_length=20, verbose_name='How active is the subject in community activities such as Motshelo, Syndicate, PTA, VDC, Mophato and development of the community that surrounds the subject?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='income_earnings',
            field=models.CharField(choices=[('None', 'No income'), ('1-199', '1-199 pula'), ('200-499', '200-499 pula'), ('500-999', '500-999 pula'), ('1000-4999', '1000-4999 pula'), ('5000-10000', '5000-10000 pula'), ('>10000', 'More than 10000 pula'), ('NOT ANSWERING', "Don't want to answer")], max_length=10, verbose_name='In the past month, how much money did the subject earn from the work they did or received in payment?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=8, verbose_name="What is the subject's marital status?"),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='number_of_spouses_f',
            field=models.IntegerField(verbose_name="How many wives does the subject's husband have (including traditional marriage), including the subject?"),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='number_of_spouses_m',
            field=models.IntegerField(verbose_name='How many wives does the subject have, including traditional marriage?'),
        ),
    ]
