# Generated by Django 2.1.1 on 2018-10-15 06:44

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('tp_screening', '0004_auto_20181005_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantscreening',
            name='created',
            field=models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='hostname_modified',
            field=edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='modified',
            field=models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='revision',
            field=django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision'),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='user_created',
            field=edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='participantscreening',
            name='user_modified',
            field=edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='community_activity',
            field=models.CharField(choices=[('VERY', 'Very Active'), ('SOMEWHAT', 'Somewhat Active'), ('NOT ACTIVE', 'Not active'), ('NOT ANSWERING', "Don't want to answer")], max_length=20, verbose_name='How active is the subject in community activities such as Motshelo, Syndicate, PTA, VDC, Mophato & development of the community that surrounds the subject?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='id',
            field=edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='number_of_spouses_f',
            field=models.IntegerField(verbose_name="How many wives does the subject's husband have(including traditional marriage), including the subject?"),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='number_of_spouses_m',
            field=models.IntegerField(verbose_name='How many wives does the subject have, includingtraditional marriage?'),
        ),
    ]
