# Generated by Django 2.1.1 on 2018-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_screening', '0005_auto_20181015_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Does subject have a guardian available?, If minor'),
        ),
    ]
