# Generated by Django 2.1.1 on 2018-10-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_screening', '0006_participantscreening_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Does subject have a guardian available?, If minor'),
        ),
    ]
