# Generated by Django 2.1.1 on 2018-10-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_screening', '0007_auto_20181015_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantscreening',
            name='community_activity',
            field=models.CharField(blank=True, choices=[('VERY', 'Very Active'), ('SOMEWHAT', 'Somewhat Active'), ('NOT ACTIVE', 'Not active'), ('NOT ANSWERING', "Don't want to answer")], max_length=20, null=True, verbose_name='How active is the subject in community activities such as Motshelo, Syndicate, PTA, VDC, Mophato & development of the community that surrounds the subject?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Is the subject currently employed?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Does subject have a guardian available?, If minor'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='income_earnings',
            field=models.CharField(blank=True, choices=[('None', 'No income'), ('1-199', '1-199 pula'), ('200-499', '200-499 pula'), ('500-999', '500-999 pula'), ('1000-4999', '1000-4999 pula'), ('5000-10000', '5000-10000 pula'), ('>10000', 'More than 10000 pula'), ('NOT ANSWERING', "Don't want to answer")], max_length=10, null=True, verbose_name='In the past month, how much money did the subject earn from the work they did or received in payment?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='living_arr',
            field=models.CharField(blank=True, choices=[('ALONE', 'Alone'), ('PARTNER', 'Partner'), ('SIBLINGS', 'Siblings'), ('OTHER', 'Other'), ('NOT ANSWERING', "Don't want to answer")], max_length=30, null=True, verbose_name='Who does the subject currently live with?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=8, null=True, verbose_name="What is the subject's marital status?"),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='number_of_spouses_f',
            field=models.IntegerField(blank=True, null=True, verbose_name="How many wives does the subject's husband have(including traditional marriage), including the subject?"),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='number_of_spouses_m',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many wives does the subject have, includingtraditional marriage?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='voted',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('DWTA', "Don't want to answer"), ('N/A', 'Not applicable')], max_length=15, null=True, verbose_name='Did the subject vote during the last local government election?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='work_type',
            field=models.CharField(blank=True, choices=[('CASUAL EMPLOYMENT', 'Casual Employment'), ('SEASONAL EMPLOYMENT', 'Seasonal Employment'), ('FW FULL TIME', 'Formal Wage (Full-Time)'), ('FW PART TIME', 'Formal Wage (Part-Time)'), ('SE AGRICULTURE', 'Self Employed in Agriculture'), ('SE FULL TIME', 'Self Employed Full Time'), ('SE PART TIME', 'Self Employed Part Time'), ('NOT ANSWERING', "Don't want to answer"), ('OTHER', 'Other')], max_length=30, null=True, verbose_name='What type of work does the subject do?'),
        ),
    ]
