# Generated by Django 2.1.1 on 2018-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_screening', '0009_auto_20181016_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantscreening',
            name='age_in_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age in years.'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Is subject a citizen of botswana?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='guardian',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Does subject have a guardian available?, If minor'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='has_witness_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Does the subject have a literate witness available with them ?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='literacy',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Is subject literate?'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='marriage_proof',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='has subject provided proof of marriage? Marriage certificate.'),
        ),
        migrations.AlterField(
            model_name='participantscreening',
            name='married_to_citizen',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='If not citizen, are they legally married to a motswana?'),
        ),
    ]
